
name: NPM Publish package Mechanic

on:
  push:
    tags:
      - "@reignmodule/mechanic-text@*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: autorize on npm
        working-directory: packages/mechanic
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - name: install
        working-directory: packages/mechanic
        run: npm ci
      - name: publish on npm
        working-directory: packages/mechanic
        run: npm publish
